### PR TITLE
Add design for provider logos. Ref #4

### PR DESCRIPTION
**Pull request by soleo**
Added the design for providers include a sketch file. Ref #4 

screenshot-localhost 8000-2016-11-12-11-30-12

### CODE REVIEW

**Comment by soleo** [comment]
@karllhughes how do you like the design?

**Comment by soleo** [comment]
screenshot-localhost 8000-2016-11-12-11-40-27

**Comment by karllhughes** [comment]
This looks awesome @soleo!

Only minor change I would make is to move it below the three text blocks. Just want to make sure people can quickly see what the project does before they dig deeper and see all the providers. What do you think?

**Comment by karllhughes** [comment]
Things also get a bit wonky on mobile
screen shot 2016-11-14 at 5 49 53 pm

**Comment by soleo** [comment]
@karllhughes I'd be okay to move the block below the about section. Do you think it would be better if I make all the logo gray? There are so many different colors on the current page.

**Comment by karllhughes** [comment]
TBH I'm not a great visual designer, so if you feel strongly about colors or greyscale I'd go with your opinion. I don't mind the colors, but I can see your point.

**Comment by soleo** [comment]
screenshot-localhost 8000-2016-11-27-22-19-33
screenshot-localhost 8000-2016-11-27-22-19-04

Fixed the layout and gray scaled the logos. cc @karllhughes

**Pull request merged**
